export const foodDatabase = [
    { name: 'Apple', calories: 52, unit: '1 medium (182g)' },
    { name: 'Banana', calories: 105, unit: '1 medium (118g)' },
    { name: 'Chicken Breast (Grilled)', calories: 165, unit: '3.5 oz (100g)' },
    { name: 'Rice (White, Cooked)', calories: 130, unit: '100g' },
    { name: 'Rice (Brown, Cooked)', calories: 111, unit: '100g' },
    { name: 'Egg (Boiled)', calories: 78, unit: '1 large' },
    { name: 'Egg (Fried)', calories: 90, unit: '1 large' },
    { name: 'Pizza (Pepperoni)', calories: 298, unit: '1 slice' },
    { name: 'Burger (Cheeseburger)', calories: 303, unit: '1 item' },
    { name: 'French Fries', calories: 312, unit: '1 medium serving' },
    { name: 'Salad (Caesar)', calories: 190, unit: '1 cup' },
    { name: 'Salmon (Baked)', calories: 206, unit: '3.5 oz (100g)' },
    { name: 'Avocado', calories: 160, unit: '1/2 medium' },
    { name: 'Oatmeal (Cooked)', calories: 158, unit: '1 cup' },
    { name: 'Greek Yogurt (Plain)', calories: 59, unit: '100g' },
    { name: 'Almonds', calories: 164, unit: '1 oz (23 almonds)' },
    { name: 'Pasta (Cooked)', calories: 131, unit: '100g' },
    { name: 'Bread (Whole Wheat)', calories: 81, unit: '1 slice' },
    { name: 'Bread (White)', calories: 66, unit: '1 slice' },
    { name: 'Milk (Whole)', calories: 150, unit: '1 cup' },
    { name: 'Coffee (Black)', calories: 2, unit: '1 cup' },
    { name: 'Cola', calories: 140, unit: '1 can (12 oz)' },
    { name: 'Beer', calories: 153, unit: '1 can (12 oz)' },
    { name: 'Wine (Red)', calories: 125, unit: '5 oz' },
    { name: 'Chocolate (Dark)', calories: 170, unit: '1 oz' },
    { name: 'Ice Cream (Vanilla)', calories: 137, unit: '1/2 cup' },
    { name: 'Steak (Beef)', calories: 271, unit: '3.5 oz (100g)' },
    { name: 'Tuna (Canned)', calories: 132, unit: '1 can' },
    { name: 'Broccoli (Steamed)', calories: 55, unit: '1 cup' },
    { name: 'Carrots (Raw)', calories: 41, unit: '1 medium' },
    { name: 'Potato (Baked)', calories: 161, unit: '1 medium' },
    { name: 'Sweet Potato (Baked)', calories: 103, unit: '1 medium' },
    { name: 'Peanut Butter', calories: 188, unit: '2 tbsp' },
    { name: 'Cheese (Cheddar)', calories: 113, unit: '1 slice (1 oz)' },
    { name: 'Orange', calories: 62, unit: '1 medium' },
    { name: 'Grapes', calories: 62, unit: '1 cup' },
    { name: 'Watermelon', calories: 30, unit: '100g' },
    { name: 'Cucumber', calories: 16, unit: '1 cup' },
    { name: 'Tomato', calories: 22, unit: '1 medium' },
    { name: 'Spinach (Raw)', calories: 7, unit: '1 cup' }
];
